# Generated by Django 4.1.4 on 2023-01-25 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_bidcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.CharField(max_length=2000),
        ),
    ]
